### ISSUE TITLE
Could not load libOpenCL.so, error 

### ISSUE THREAD

**Issue by select** [SonarSonic/DrawingBotV3#128]
**Describe the bug**
```
> /opt/drawingbotv3/bin/DrawingBotV3-Premium
Could not load libOpenCL.so, error libOpenCL.so: cannot open shared object file: No such file or directory
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not initialize native OpenCL library. Implementation library could not be loaded
	at org.jocl.LibInitializer.initNativeLibrary(LibInitializer.java:74)
	at org.jocl.CL.loadNativeLibrary(CL.java:66)
	at org.jocl.CL.<clinit>(CL.java:51)
	at drawingbot.k.c.b.g.a(Unknown Source)
	at drawingbot.k.c.b.g.<clinit>(Unknown Source)
	at drawingbot.k.a.<init>(Unknown Source)
	at drawingbot.k.a.<clinit>(Unknown Source)
	at drawingbot.LauncherPremium.main(Unknown Source)
```

**To Reproduce**
Download premium package, install it, try to start it

**Expected behavior**
starts

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**DrawingBotV3 Version**
DrawingBotV3-Premium-1.6.13-stable-linux.deb

**Operating System**
Ubuntu 22.04.4 LTS

**Additional info**
fixed by
```
sudo apt install ocl-icd-opencl-dev
```
this should be a package dependency!

**Comment by SonarSonic** [comment]
Fixed in dev: added ocl-icd-opencl-dev to the linux .deb dependencies
